### ISSUE TITLE
Rework Org Agenda/Todo Config

### ISSUE THREAD

**Issue by nfitzen** [nfitzen/doom-emacs-config#1]
I think there's some work to be done with the way I have org-agenda set up. In particular:

- [ ] Rework org-super-agenda categories
- [ ] Create new list of TODO entry types
- [ ] Tweak config for how entries show up in agenda
    - Not sure what, but I'm sure there's something nice.
